#!/usr/bin/env perl 

use strict; 
use warnings; 

use Getopt::Long;  
use Pod::Usage; 

use MD   qw( save_traj retrieve_traj normalize ); 
use VASP qw( read_md print_md );  

my @usages = qw( NAME SYSNOPSIS OPTIONS NOTE );  

# POD 
=head1 NAME 

mdprofile.pl: extract the potential profile from OSZICAR  

=head1 SYNOPSIS

mdprofile.pl [-h]

=head1 OPTIONS

=over 8

=item B<-h>

Print the help message and exit.

=back

=head1 NOTE 

If MD is terminated unexpectedly, there will be mistmatch between trajectry and profile.   
Thus, a trajectory generated by xdatcar.pl is mandantory for consistency check. 

=cut

my $help = 0; 

# parse optional arguments 
GetOptions('h' => \$help) or pod2usage(-verbose => 1); 

# help message
if ( $help ) { pod2usage(-verbose => 99, -section => \@usages) } 

# default 
my $trajectory = 'traj.dat'; 
my $profile    = 'profile.dat'; 

# profile
my %md   = read_md('OSZICAR'); 

# pre-generated trajectory for sanity check
my %traj = retrieve_traj($trajectory);  

# synchronization two hashses probably due to early job termination
if ( normalize(\%md, \%traj) ) { 
    print "=> Updating trajectry file\n"; 
    save_traj(\%traj => $trajectory); 
    print "\n"; 
}

# profile.dat
print "=> Potential profile is written to $profile\n"; 
print_md(\%md => $profile);  
